export const OPPORTUNITY_TYPES = [
  "TENDER",
  "RFP",
  "RFQ",
  "CONTRACT",
  "GRANT",
  "FUNDING",
  "JOB",
  "INTERNSHIP",
  "SCHOLARSHIP",
  "FELLOWSHIP",
  "ACCELERATOR",
  "INCUBATOR",
  "COMPETITION",
  "HACKATHON",
  "TRAINING",
  "RESEARCH",
  "PARTNERSHIP",
  "INVESTMENT",
  "CONSULTANCY",
  "SUPPLIER",
  "VENDOR",
  "CALL_FOR_PROPOSALS",
  "OTHER",
] as const;

export type OpportunityTypeKey = (typeof OPPORTUNITY_TYPES)[number];

export const OPPORTUNITY_TYPE_LABELS: Record<OpportunityTypeKey, string> = {
  TENDER: "Tender",
  RFP: "Request for Proposal",
  RFQ: "Request for Quotation",
  CONTRACT: "Contract",
  GRANT: "Grant",
  FUNDING: "Funding",
  JOB: "Job",
  INTERNSHIP: "Internship",
  SCHOLARSHIP: "Scholarship",
  FELLOWSHIP: "Fellowship",
  ACCELERATOR: "Accelerator",
  INCUBATOR: "Incubator",
  COMPETITION: "Competition",
  HACKATHON: "Hackathon",
  TRAINING: "Training",
  RESEARCH: "Research",
  PARTNERSHIP: "Partnership",
  INVESTMENT: "Investment",
  CONSULTANCY: "Consultancy",
  SUPPLIER: "Supplier",
  VENDOR: "Vendor",
  CALL_FOR_PROPOSALS: "Call for Proposals",
  OTHER: "Other",
};