import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import dnaRoutes from "./dna.routes";
import opportunityRoutes from "./opportunity.routes";
import searchRoutes from "./search.routes";
import matchingRoutes from "./matching.routes";
import radarRoutes from "./radar.routes";
import watchlistRoutes from "./watchlist.routes";
import savedRoutes from "./saved.routes";
import pipelineRoutes from "./pipeline.routes";
import notificationRoutes from "./notification.routes";
import analyticsRoutes from "./analytics.routes";
import aiRoutes from "./ai.routes";
import documentRoutes from "./document.routes";
import sourceRoutes from "./source.routes";
import actorRunRoutes from "./actorRun.routes";
import duplicateRoutes from "./duplicate.routes";
import changeRoutes from "./change.routes";
import organizationRoutes from "./organization.routes";
import apiKeyRoutes from "./apiKey.routes";
import webhookRoutes from "./webhook.routes";
import auditLogRoutes from "./auditLog.routes";
import adminRoutes from "./admin.routes";
import healthRoutes from "./health.routes";

const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/dna", dnaRoutes);
router.use("/opportunities", opportunityRoutes);
router.use("/search", searchRoutes);
router.use("/matches", matchingRoutes);
router.use("/radar", radarRoutes);
router.use("/watchlist", watchlistRoutes);
router.use("/saved", savedRoutes);
router.use("/pipeline", pipelineRoutes);
router.use("/notifications", notificationRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/ai", aiRoutes);
router.use("/documents", documentRoutes);
router.use("/sources", sourceRoutes);
router.use("/actor-runs", actorRunRoutes);
router.use("/duplicates", duplicateRoutes);
router.use("/changes", changeRoutes);
router.use("/organizations", organizationRoutes);
router.use("/api-keys", apiKeyRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/admin", adminRoutes);

export default router;