import { Info } from "lucide-react";
import { cn } from "../../utils/strings";

export interface AiDisclaimerProps {
  className?: string;
  variant?: "default" | "inline";
}

export function AiDisclaimer({ className, variant = "default" }: AiDisclaimerProps) {
  if (variant === "inline") {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1 text-[11px] text-neutral-500",
          className,
        )}
      >
        <Info aria-hidden className="h-3 w-3" />
        AI-generated. Verify against the official source.
      </span>
    );
  }

  return (
    <div
      className={cn(
        "flex items-start gap-2 rounded-md bg-neutral-50 px-3 py-2 text-xs text-neutral-500",
        className,
      )}
    >
      <Info aria-hidden className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <p>
        This content is generated by AI to help you understand the
        opportunity. It is not official and may contain errors. Always verify
        against the original source before acting.
      </p>
    </div>
  );
}