export enum AiTaskType {
  CLASSIFICATION = "CLASSIFICATION",
  SUMMARY = "SUMMARY",
  ELIGIBILITY = "ELIGIBILITY",
  REQUIREMENTS = "REQUIREMENTS",
  DOCUMENT = "DOCUMENT",
  RISK = "RISK",
  RECOMMENDATIONS = "RECOMMENDATIONS",
  ANALYST = "ANALYST",
  SEARCH_INTENT = "SEARCH_INTENT",
  OTHER = "OTHER",
}