export enum NotificationType {
  NEW_MATCH = "NEW_MATCH",
  DEADLINE_SOON = "DEADLINE_SOON",
  DEADLINE_CHANGED = "DEADLINE_CHANGED",
  REQUIREMENT_CHANGED = "REQUIREMENT_CHANGED",
  OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED",
  OPPORTUNITY_EXPIRED = "OPPORTUNITY_EXPIRED",
  SOURCE_FAILED = "SOURCE_FAILED",
  SOURCE_HEALTH_WARNING = "SOURCE_HEALTH_WARNING",
  PIPELINE_REMINDER = "PIPELINE_REMINDER",
  SYSTEM = "SYSTEM",
}