export enum SourceType {
  GOVERNMENT = "GOVERNMENT",
  PROCUREMENT_PORTAL = "PROCUREMENT_PORTAL",
  UNIVERSITY = "UNIVERSITY",
  NGO = "NGO",
  FOUNDATION = "FOUNDATION",
  ACCELERATOR = "ACCELERATOR",
  GRANT_PORTAL = "GRANT_PORTAL",
  JOB_BOARD = "JOB_BOARD",
  SCHOLARSHIP_PORTAL = "SCHOLARSHIP_PORTAL",
  DEVELOPMENT_ORG = "DEVELOPMENT_ORG",
  PRIVATE_COMPANY = "PRIVATE_COMPANY",
  OTHER = "OTHER",
}