export enum SystemLifecycle {
  DISCOVERED = "DISCOVERED",
  RAW = "RAW",
  NORMALIZED = "NORMALIZED",
  VALIDATED = "VALIDATED",
  DEDUPLICATED = "DEDUPLICATED",
  VERIFIED = "VERIFIED",
  ANALYZED = "ANALYZED",
  PUBLISHED = "PUBLISHED",
  MONITORED = "MONITORED",
  UPDATED = "UPDATED",
  EXPIRED = "EXPIRED",
}