export enum UserLifecycle {
  DISCOVERED = "DISCOVERED",
  REVIEWING = "REVIEWING",
  QUALIFIED = "QUALIFIED",
  PREPARING = "PREPARING",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  WON = "WON",
  LOST = "LOST",
  WITHDRAWN = "WITHDRAWN",
  DISQUALIFIED = "DISQUALIFIED",
  EXPIRED = "EXPIRED",
}