export const OPPORTUNITY_CATEGORIES = {
  PROCUREMENT: "PROCUREMENT",
  CONTRACTS: "CONTRACTS",
  GRANTS: "GRANTS",
  FUNDING: "FUNDING",
  EMPLOYMENT: "EMPLOYMENT",
  INTERNSHIPS: "INTERNSHIPS",
  SCHOLARSHIPS: "SCHOLARSHIPS",
  FELLOWSHIPS: "FELLOWSHIPS",
  ACCELERATORS: "ACCELERATORS",
  INCUBATORS: "INCUBATORS",
  COMPETITIONS: "COMPETITIONS",
  TRAINING: "TRAINING",
  RESEARCH: "RESEARCH",
  PARTNERSHIPS: "PARTNERSHIPS",
  INVESTMENT: "INVESTMENT",
  DEVELOPMENT: "DEVELOPMENT",
  OTHER: "OTHER",
} as const;

export type OpportunityCategoryKey = keyof typeof OPPORTUNITY_CATEGORIES;

export const OPPORTUNITY_CATEGORY_LABELS: Record<OpportunityCategoryKey, string> = {
  PROCUREMENT: "Procurement",
  CONTRACTS: "Contracts",
  GRANTS: "Grants",
  FUNDING: "Funding",
  EMPLOYMENT: "Jobs",
  INTERNSHIPS: "Internships",
  SCHOLARSHIPS: "Scholarships",
  FELLOWSHIPS: "Fellowships",
  ACCELERATORS: "Accelerators",
  INCUBATORS: "Incubators",
  COMPETITIONS: "Competitions",
  TRAINING: "Training",
  RESEARCH: "Research",
  PARTNERSHIPS: "Partnerships",
  INVESTMENT: "Investment",
  DEVELOPMENT: "Development",
  OTHER: "Other",
};

export const OPPORTUNITY_TYPES = {
  TENDER: "TENDER",
  RFP: "RFP",
  RFQ: "RFQ",
  CONTRACT: "CONTRACT",
  GRANT: "GRANT",
  FUNDING: "FUNDING",
  JOB: "JOB",
  INTERNSHIP: "INTERNSHIP",
  SCHOLARSHIP: "SCHOLARSHIP",
  FELLOWSHIP: "FELLOWSHIP",
  ACCELERATOR: "ACCELERATOR",
  INCUBATOR: "INCUBATOR",
  COMPETITION: "COMPETITION",
  HACKATHON: "HACKATHON",
  TRAINING: "TRAINING",
  RESEARCH: "RESEARCH",
  PARTNERSHIP: "PARTNERSHIP",
  INVESTMENT: "INVESTMENT",
  CONSULTANCY: "CONSULTANCY",
  SUPPLIER: "SUPPLIER",
  VENDOR: "VENDOR",
  CALL_FOR_PROPOSALS: "CALL_FOR_PROPOSALS",
  OTHER: "OTHER",
} as const;

export type OpportunityTypeKey = keyof typeof OPPORTUNITY_TYPES;

export const OPPORTUNITY_TYPE_LABELS: Record<OpportunityTypeKey, string> = {
  TENDER: "Tender",
  RFP: "Request for Proposal",
  RFQ: "Request for Quotation",
  CONTRACT: "Contract",
  GRANT: "Grant",
  FUNDING: "Funding",
  JOB: "Job",
  INTERNSHIP: "Internship",
  SCHOLARSHIP: "Scholarship",
  FELLOWSHIP: "Fellowship",
  ACCELERATOR: "Accelerator",
  INCUBATOR: "Incubator",
  COMPETITION: "Competition",
  HACKATHON: "Hackathon",
  TRAINING: "Training",
  RESEARCH: "Research",
  PARTNERSHIP: "Partnership",
  INVESTMENT: "Investment",
  CONSULTANCY: "Consultancy",
  SUPPLIER: "Supplier",
  VENDOR: "Vendor",
  CALL_FOR_PROPOSALS: "Call for Proposals",
  OTHER: "Other",
};