export const NOTIFICATION_TYPES = {
  NEW_MATCH: "NEW_MATCH",
  DEADLINE_SOON: "DEADLINE_SOON",
  DEADLINE_CHANGED: "DEADLINE_CHANGED",
  REQUIREMENT_CHANGED: "REQUIREMENT_CHANGED",
  OPPORTUNITY_UPDATED: "OPPORTUNITY_UPDATED",
  OPPORTUNITY_EXPIRED: "OPPORTUNITY_EXPIRED",
  SOURCE_FAILED: "SOURCE_FAILED",
  SOURCE_HEALTH_WARNING: "SOURCE_HEALTH_WARNING",
  PIPELINE_REMINDER: "PIPELINE_REMINDER",
  SYSTEM: "SYSTEM",
} as const;

export type NotificationTypeKey = keyof typeof NOTIFICATION_TYPES;

export const NOTIFICATION_CHANNELS = {
  IN_APP: "IN_APP",
  EMAIL: "EMAIL",
  PUSH: "PUSH",
  WEBHOOK: "WEBHOOK",
} as const;

export type NotificationChannelKey = keyof typeof NOTIFICATION_CHANNELS;

export const DELIVERY_STATUS = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
} as const;

export type DeliveryStatusKey = keyof typeof DELIVERY_STATUS;